# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Scrubber
version:      0.08
version_from: Scrubber.pm
installdirs:  site
requires:
    HTML::Parser:                  3
    Test:                          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
