#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Scrubber
version:      0.03
version_from: Scrubber.pm
installdirs:  site
requires:
    HTML::Parser:                  3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_06
